### ISSUE TITLE
bricked after update

### ISSUE THREAD

**Issue by 9a4db** [erainstruments/erasynth-firmware#3]
Please suggest solution :)

After firmware update device remain with green led on, communication over RS232 not possible

Board info available:
BN: Arduino Due (Programming Port)
VID: 2341
PID: 003D
SN: 75533353437351A050B0

Update ->
Archiving built core (caching) in: C:\Users\SUMY~1\AppData\Local\Temp\arduino_cache_403224\core\core_arduino_sam_arduino_due_x_dbg_36f50055e622fdd62b4826e226558e71.a
Sketch uses 22448 bytes (4%) of program storage space. Maximum is 524288 bytes.
Atmel SMART device 0x285e0a60 found
Erase flash
done in 0.033 seconds

Write 24716 bytes to flash (97 pages)

[                              ] 0% (0/97 pages)
[==                            ] 9% (9/97 pages)
[=====                         ] 18% (18/97 pages)
[========                      ] 27% (27/97 pages)
[===========                   ] 37% (36/97 pages)
[=============                 ] 46% (45/97 pages)
[================              ] 55% (54/97 pages)
[===================           ] 64% (63/97 pages)
[======================        ] 74% (72/97 pages)
[=========================     ] 83% (81/97 pages)
[===========================   ] 92% (90/97 pages)
[==============================] 100% (97/97 pages)
done in 4.766 seconds

Verify 24716 bytes of flash

[                              ] 0% (0/97 pages)
[==                            ] 9% (9/97 pages)
[=====                         ] 18% (18/97 pages)
[========                      ] 27% (27/97 pages)
[===========                   ] 37% (36/97 pages)
[=============                 ] 46% (45/97 pages)
[================              ] 55% (54/97 pages)
[===================           ] 64% (63/97 pages)
[======================        ] 74% (72/97 pages)
[=========================     ] 83% (81/97 pages)
[===========================   ] 92% (90/97 pages)
[==============================] 100% (97/97 pages)
Verify successful
done in 4.372 seconds
Set boot flash true
CPU reset.

**Comment by berjk** [comment]
Which ERASynth are you using? (ERASynth, ERASynth+ or ERASynth++ )
Have you followed our firmware update instructions? ( https://github.com/erainstruments/erasynth-docs/blob/master/erasynth-firmware-update-instructions.pdf )

It seems like you uploaded a empty skecth. Your description says that it consists of 24716 bytes (97 pages). Our firmware contains more than 700 pages.

**Comment by 9a4db** [comment]
Using ERASynth+ SN0015
Screen copy before update:
![erasynth_screem](https://user-images.githubusercontent.com/30326618/43061280-e8f4a91a-8e54-11e8-9211-af660c56d944.jpg)

Yes, update instructions followed.
Just, was not able to run last step ->
13-) After a successful upload it is recommended to apply a FACTORY RESET (>PR with carriage return) if a modification is made related with the embedded non-volatile memory (FRAM) that stores the settings of the device.

OK, than must try one more time.

**Comment by 9a4db** [comment]
Second try:
Archiving built core (caching) in: C:\Users\SUCKMY~1\AppData\Local\Temp\arduino_cache_841237\core\core_arduino_sam_arduino_due_x_dbg_36f50055e622fdd62b4826e226558e71.a
Sketch uses 339196 bytes (64%) of program storage space. Maximum is 524288 bytes.
Atmel SMART device 0x285e0a60 found
Erase flash
done in 0.032 seconds

Write 344476 bytes to flash (1346 pages)

[                              ] 0% (0/1346 pages)
[==                            ] 9% (134/1346 pages)
[=====                         ] 19% (268/1346 pages)
[========                      ] 29% (402/1346 pages)
[===========                   ] 39% (536/1346 pages)
[==============                ] 49% (670/1346 pages)
[=================             ] 59% (804/1346 pages)
[====================          ] 69% (938/1346 pages)
[=======================       ] 79% (1072/1346 pages)
[==========================    ] 89% (1206/1346 pages)
[============================= ] 99% (1340/1346 pages)
[==============================] 100% (1346/1346 pages)
done in 66.171 seconds

Verify 344476 bytes of flash

[                              ] 0% (0/1346 pages)
[==                            ] 9% (134/1346 pages)
[=====                         ] 19% (268/1346 pages)
[========                      ] 29% (402/1346 pages)
[===========                   ] 39% (536/1346 pages)
[==============                ] 49% (670/1346 pages)
[=================             ] 59% (804/1346 pages)
[====================          ] 69% (938/1346 pages)
[=======================       ] 79% (1072/1346 pages)
[==========================    ] 89% (1206/1346 pages)
[============================= ] 99% (1340/1346 pages)
[==============================] 100% (1346/1346 pages)
Verify successful
done in 60.658 seconds
Set boot flash true
CPU reset.

Now Green ON, Red BLINK
Good sign 👍

**Comment by 9a4db** [comment]
Serial comm working!
Hot spot working!
Thank you for prompt assistance.
